spring:
  application:
    name: capstone-backend
  datasource:
    master:
      url: ${DB_MASTER_URL:jdbc:postgresql://localhost:5432/bank_db}
      username: ${DB_MASTER_USER:postgres}
      password: ${DB_MASTER_PASS:password}
      driver-class-name: org.postgresql.Driver
      hikari:
        pool-name: MasterHikariCP
        maximum-pool-size: 10
    replica:
      url: ${DB_REPLICA_URL:jdbc:postgresql://localhost:5432/bank_db}
      username: ${DB_REPLICA_USER:postgres}
      password: ${DB_REPLICA_PASS:password}
      driver-class-name: org.postgresql.Driver
      hikari:
        pool-name: ReplicaHikariCP
        maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always
