global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:2112']

  - job_name: 'balance-service'
    static_configs:
      - targets: ['balance-service:2112']

  - job_name: 'transaction-service'
    static_configs:
      - targets: ['transaction-service:2112']
