// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: balance/balance.proto

package balance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Diambil dari token JWT oleh API Gateway atau middleware
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceRequest) Reset() {
	*x = BalanceRequest{}
	mi := &file_balance_balance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceRequest) ProtoMessage() {}

func (x *BalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_balance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceRequest.ProtoReflect.Descriptor instead.
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return file_balance_balance_proto_rawDescGZIP(), []int{0}
}

func (x *BalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type BalanceResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StatusCode     int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CurrentBalance float64                `protobuf:"fixed64,3,opt,name=current_balance,json=currentBalance,proto3" json:"current_balance,omitempty"`
	AccountNumber  string                 `protobuf:"bytes,4,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BalanceResponse) Reset() {
	*x = BalanceResponse{}
	mi := &file_balance_balance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResponse) ProtoMessage() {}

func (x *BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balance_balance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResponse.ProtoReflect.Descriptor instead.
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return file_balance_balance_proto_rawDescGZIP(), []int{1}
}

func (x *BalanceResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *BalanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BalanceResponse) GetCurrentBalance() float64 {
	if x != nil {
		return x.CurrentBalance
	}
	return 0
}

func (x *BalanceResponse) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

var File_balance_balance_proto protoreflect.FileDescriptor

const file_balance_balance_proto_rawDesc = "" +
	"\n" +
	"\x15balance/balance.proto\x12\abalance\")\n" +
	"\x0eBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x9c\x01\n" +
	"\x0fBalanceResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fcurrent_balance\x18\x03 \x01(\x01R\x0ecurrentBalance\x12%\n" +
	"\x0eaccount_number\x18\x04 \x01(\tR\raccountNumber2U\n" +
	"\x0eBalanceService\x12C\n" +
	"\fCheckBalance\x12\x17.balance.BalanceRequest\x1a\x18.balance.BalanceResponse\"\x00B\x18Z\x16capstone/proto/balanceb\x06proto3"

var (
	file_balance_balance_proto_rawDescOnce sync.Once
	file_balance_balance_proto_rawDescData []byte
)

func file_balance_balance_proto_rawDescGZIP() []byte {
	file_balance_balance_proto_rawDescOnce.Do(func() {
		file_balance_balance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_balance_balance_proto_rawDesc), len(file_balance_balance_proto_rawDesc)))
	})
	return file_balance_balance_proto_rawDescData
}

var file_balance_balance_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_balance_balance_proto_goTypes = []any{
	(*BalanceRequest)(nil),  // 0: balance.BalanceRequest
	(*BalanceResponse)(nil), // 1: balance.BalanceResponse
}
var file_balance_balance_proto_depIdxs = []int32{
	0, // 0: balance.BalanceService.CheckBalance:input_type -> balance.BalanceRequest
	1, // 1: balance.BalanceService.CheckBalance:output_type -> balance.BalanceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_balance_balance_proto_init() }
func file_balance_balance_proto_init() {
	if File_balance_balance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_balance_balance_proto_rawDesc), len(file_balance_balance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_balance_balance_proto_goTypes,
		DependencyIndexes: file_balance_balance_proto_depIdxs,
		MessageInfos:      file_balance_balance_proto_msgTypes,
	}.Build()
	File_balance_balance_proto = out.File
	file_balance_balance_proto_goTypes = nil
	file_balance_balance_proto_depIdxs = nil
}
